### ISSUE TITLE
Spicy-dns error: expecting 1 bytes for unpacking value (/usr/local/zeek/var/lib/zkg/clones/package/spicy-dns/analyzer/analyzer.spicy:109:10)

### ISSUE THREAD

**Issue by Politie-SOC** [zeek/spicy-dns#10]
Hi,

I found another Spicy-DNS error which occurs numerous times in our logs:
   expecting 1 bytes for unpacking value (/usr/local/zeek/var/lib/zkg/clones/package/spicy-dns/analyzer/analyzer.spicy:109:10) 

DNS response packet caused above error, see attached pcap with 2 packets.
Plugin version v0.0.6

Thanks for looking into this.

[unpack_error:109:10.pcap.gz](https://github.com/zeek/spicy-dns/files/12595511/unpack_error.109.10.pcap.gz)

**Comment by bbannier** [comment]
@Politie-SOC, it looks like the PCAP you attached above contains no traffic and does not trigger the issue for me. Could you attach another PCAP which shows this behavior?

**Comment by Politie-SOC** [comment]
Sorry, that was the wrong file I attached.
The following should be the one.
[analyzer.spicy:109:10.pcap.gz](https://github.com/zeek/spicy-dns/files/12596080/analyzer.spicy.109.10.pcap.gz)
